### PR TITLE
Created Aspect Activity

### PR DESCRIPTION
**Pull request by chaedri**

### CODE REVIEW

**Comment by wenzeslaus** [comment]
The CI is good now. Let us know if you plan further changes or cleanup of the functions you don't wish to use.

One note: You made the PR from your main branch rather than a new dedicated branch. That's not an issue for your first PR, but you will need to make some fix before you do another PR. If all your work is saved elsewhere, deleting your fork and the local repo is [a fine fix](https://m.xkcd.com/1597/). Probably `git switch` missing somewhere.

**Comment by chaedri** [comment]
Ah, yep, I definitely forgot to make a new branch. I have a local repo so I'll try that fix for next time. Thanks!

**Review by petrasovaa — CHANGES_REQUESTED** [review]
You are computing a lot of things that are not used, e.g. the slope layer, and points. Please remove those. Computing aspect is fine, although I would like to see something little more exciting:)

**Comment by chaedri** [comment]
This was an old Pull Request from February. It's in the wrong branch (chaedri/main) and doesn't have my activity.

**Pull request closed without merging**
